export const districts = [
  /* =======================
     VIENTIANE CAPITAL (01000)
     ======================= */
  {
    code: '1-01',
    province_code: '01',
    name_en: 'Chanthabuly District',
    name_la: 'ເມືອງຈັນທະບູລີ',
    name_th: 'จันทบุรี',
    name_zh: '占塔布里',
    postal_code: '01000',
    is_verified: true,
  },
  {
    code: '1-02',
    province_code: '01',
    name_en: 'Sikhottabong District',
    name_la: 'ເມືອງສີໂຄດຕະບອງ',
    name_th: 'ศรีโคตรบอง',
    name_zh: '西科塔邦',
    postal_code: '01000',
    is_verified: true,
  },
  {
    code: '1-03',
    province_code: '01',
    name_en: 'Xaysetha District',
    name_la: 'ເມືອງໄຊເສດຖາ',
    name_th: 'ไซเสดถา',
    name_zh: '赛色塔',
    postal_code: '01000',
    is_verified: true,
  },
  {
    code: '1-04',
    province_code: '01',
    name_en: 'Sisattanak District',
    name_la: 'ເມືອງສີສັດຕະນາກ',
    name_th: 'ศรีสัตตนาก',
    name_zh: '西萨塔纳',
    postal_code: '01000',
    is_verified: true,
  },
  {
    code: '1-05',
    province_code: '01',
    name_en: 'Naxaithong District',
    name_la: 'ເມືອງນາຊາຍທອງ',
    name_th: 'นาซายทอง',
    name_zh: '纳赛通',
    postal_code: '01000',
    is_verified: true,
  },
  {
    code: '1-06',
    province_code: '01',
    name_en: 'Xaythany District',
    name_la: 'ເມືອງໄຊທານີ',
    name_th: 'ไซธานี',
    name_zh: '赛塔尼',
    postal_code: '01000',
    is_verified: true,
  },
  {
    code: '1-07',
    province_code: '01',
    name_en: 'Hadxayfong District',
    name_la: 'ເມືອງຫາດຊາຍຟອງ',
    name_th: 'หาดทรายฟอง',
    name_zh: '哈赛丰',
    postal_code: '01000',
    is_verified: true,
  },
  {
    code: '1-08',
    province_code: '01',
    name_en: 'Sangthong District',
    name_la: 'ເມືອງສັງທອງ',
    name_th: 'สังทอง',
    name_zh: '桑通',
    postal_code: '01000',
    is_verified: true,
  },
  {
    code: '1-09',
    province_code: '01',
    name_en: 'Mayparkngum District',
    name_la: 'ເມືອງປາກງື່ມ',
    name_th: 'ปากงึม',
    name_zh: '帕康',
    postal_code: '01000',
    is_verified: true,
  },

  /* =======================
     PHONGSALY (02000)
     ======================= */
  {
    code: '2-01',
    province_code: '02',
    name_en: 'Phongsaly District',
    name_la: 'ເມືອງຜົ້ງສາລີ',
    name_th: 'ผ้งสาลี',
    name_zh: '丰沙里',
    postal_code: '02000',
    is_verified: true,
  },
  {
    code: '2-02',
    province_code: '02',
    name_en: 'May District',
    name_la: 'ເມືອງໃໝ່',
    name_th: 'เมืองใหม่',
    name_zh: '迈县',
    postal_code: '02000',
    is_verified: true,
  },
  {
    code: '2-03',
    province_code: '02',
    name_en: 'Khoua District',
    name_la: 'ເມືອງຂວາ',
    name_th: 'ขวา',
    name_zh: '库瓦',
    postal_code: '02000',
    is_verified: true,
  },
  {
    code: '2-04',
    province_code: '02',
    name_en: 'Samphanh District',
    name_la: 'ເມືອງສຳພັນ',
    name_th: 'สัมพันธ์',
    name_zh: '三潘',
    postal_code: '02000',
    is_verified: true,
  },
  {
    code: '2-05',
    province_code: '02',
    name_en: 'Boun Neua District',
    name_la: 'ເມືອງບຸນເໜືອ',
    name_th: 'บุญเหนือ',
    name_zh: '奔纽',
    postal_code: '02000',
    is_verified: true,
  },
  {
    code: '2-06',
    province_code: '02',
    name_en: 'Yot Ou District',
    name_la: 'ເມືອງຍອດອູ',
    name_th: 'ยอดอู',
    name_zh: '约乌',
    postal_code: '02000',
    is_verified: true,
  },
  {
    code: '2-07',
    province_code: '02',
    name_en: 'Boun Tay District',
    name_la: 'ເມືອງບຸນໃຕ້',
    name_th: 'บุญใต้',
    name_zh: '奔泰',
    postal_code: '02000',
    is_verified: true,
  },

  /* =======================
     LUANG NAMTHA (03000)
     ======================= */
  {
    code: '3-01',
    province_code: '03',
    name_en: 'Namtha District',
    name_la: 'ເມືອງຫຼວງນໍ້າທາ',
    name_th: 'หลวงน้ำทา',
    name_zh: '琅南塔',
    postal_code: '03000',
    is_verified: true,
  },
  {
    code: '3-02',
    province_code: '03',
    name_en: 'Sing District',
    name_la: 'ເມືອງສີງ',
    name_th: 'สิง',
    name_zh: '孟辛',
    postal_code: '03000',
    is_verified: true,
  },
  {
    code: '3-03',
    province_code: '03',
    name_en: 'Long District',
    name_la: 'ເມືອງລອງ',
    name_th: 'ลอง',
    name_zh: '龙县',
    postal_code: '03000',
    is_verified: true,
  },
  {
    code: '3-04',
    province_code: '03',
    name_en: 'Viengphoukha District',
    name_la: 'ເມືອງວຽງພູຄາ',
    name_th: 'เวียงภูคา',
    name_zh: '文普卡',
    postal_code: '03000',
    is_verified: true,
  },
  {
    code: '3-05',
    province_code: '03',
    name_en: 'Na Le District',
    name_la: 'ເມືອງນາແລ',
    name_th: 'นาแล',
    name_zh: '纳勒',
    postal_code: '03000',
    is_verified: true,
  },

  /* =======================
     OUDOMXAY (04000)
     ======================= */
  {
    code: '4-01',
    province_code: '04',
    name_en: 'Xay District',
    name_la: 'ເມືອງໄຊ',
    name_th: 'ไซ',
    name_zh: '赛县',
    postal_code: '04000',
    is_verified: true,
  },
  {
    code: '4-02',
    province_code: '04',
    name_en: 'La District',
    name_la: 'ເມືອງຫຼາ',
    name_th: 'หลา',
    name_zh: '拉县',
    postal_code: '04000',
    is_verified: true,
  },
  {
    code: '4-03',
    province_code: '04',
    name_en: 'Na Mo District',
    name_la: 'ເມືອງນາໝໍ້',
    name_th: 'นาโม่',
    name_zh: '纳莫',
    postal_code: '04000',
    is_verified: true,
  },
  {
    code: '4-04',
    province_code: '04',
    name_en: 'Nga District',
    name_la: 'ເມືອງງາ',
    name_th: 'งา',
    name_zh: '阿县',
    postal_code: '04000',
    is_verified: true,
  },
  {
    code: '4-05',
    province_code: '04',
    name_en: 'Beng District',
    name_la: 'ເມືອງແບ່ງ',
    name_th: 'แบ่ง',
    name_zh: '本县',
    postal_code: '04000',
    is_verified: true,
  },
  {
    code: '4-06',
    province_code: '04',
    name_en: 'Houne District',
    name_la: 'ເມືອງຮຸນ',
    name_th: 'ฮุน',
    name_zh: '洪县',
    postal_code: '04000',
    is_verified: true,
  },
  {
    code: '4-07',
    province_code: '04',
    name_en: 'Pak Beng District',
    name_la: 'ເມືອງປາກແບ່ງ',
    name_th: 'ปากแบ่ง',
    name_zh: '帕本',
    postal_code: '04000',
    is_verified: true,
  },

  /* =======================
   BOKEO (05)
   ======================= */
  {
    code: '5-01',
    province_code: '05',
    name_en: 'Houayxay District',
    name_la: 'ເມືອງຫ້ວຍຊາຍ',
    name_th: 'ห้วยไซ',
    name_zh: '霍塞',
    postal_code: '51000',
    is_verified: true,
  },
  {
    code: '5-02',
    province_code: '05',
    name_en: 'Ton Pheung District',
    name_la: 'ເມືອງຕົ້ນເຜິ້ງ',
    name_th: 'ต้นเพ็ง',
    name_zh: '吞朋',
    postal_code: '51000',
    is_verified: true,
  },
  {
    code: '5-03',
    province_code: '05',
    name_en: 'Meung District',
    name_la: 'ເມືອງເມິງ',
    name_th: 'เมิง',
    name_zh: '蒙',
    postal_code: '51000',
    is_verified: true,
  },
  {
    code: '5-04',
    province_code: '05',
    name_en: 'Pha Oudom District',
    name_la: 'ເມືອງຜາອຸດົມ',
    name_th: 'ผาอุดม',
    name_zh: '帕乌多姆',
    postal_code: '51000',
    is_verified: true,
  },
  {
    code: '5-05',
    province_code: '05',
    name_en: 'Pak Tha District',
    name_la: 'ເມືອງປາກທາ',
    name_th: 'ปากท่า',
    name_zh: '帕塔',
    postal_code: '51000',
    is_verified: true,
  },

  /* =======================
   LUANG PRABANG (06)
   ======================= */
  {
    code: '6-01',
    province_code: '06',
    name_en: 'Luang Prabang District',
    name_la: 'ເມືອງຫຼວງພະບາງ',
    name_th: 'หลวงพระบาง',
    name_zh: '琅勃拉邦',
    postal_code: '06000',
    is_verified: true,
  },
  {
    code: '6-02',
    province_code: '06',
    name_en: 'Xiengngeun District',
    name_la: 'ເມືອງຊຽງເງິນ',
    name_th: 'เชียงเงิน',
    name_zh: '显根',
    postal_code: '06000',
    is_verified: true,
  },
  {
    code: '6-03',
    province_code: '06',
    name_en: 'Nane District',
    name_la: 'ເມືອງນານ',
    name_th: 'น่าน',
    name_zh: '南',
    postal_code: '06000',
    is_verified: true,
  },
  {
    code: '6-04',
    province_code: '06',
    name_en: 'Pak Ou District',
    name_la: 'ເມືອງປາກອູ',
    name_th: 'ปากอู',
    name_zh: '帕欧',
    postal_code: '06000',
    is_verified: true,
  },
  {
    code: '6-05',
    province_code: '06',
    name_en: 'Nam Bak District',
    name_la: 'ເມືອງນ້າບາກ',
    name_th: 'น้ำบาก',
    name_zh: '南巴克',
    postal_code: '06000',
    is_verified: true,
  },
  {
    code: '6-06',
    province_code: '06',
    name_en: 'Ngoy District',
    name_la: 'ເມືອງງອຍ',
    name_th: 'งอย',
    name_zh: '昂艾',
    postal_code: '06000',
    is_verified: true,
  },
  {
    code: '6-07',
    province_code: '06',
    name_en: 'Pak Seng District',
    name_la: 'ເມືອງປາກແຊງ',
    name_th: 'ปากแซง',
    name_zh: '帕生',
    postal_code: '06000',
    is_verified: true,
  },
  {
    code: '6-08',
    province_code: '06',
    name_en: 'Phonxay District',
    name_la: 'ເມືອງໂພນໄຊ',
    name_th: 'โพนไชย',
    name_zh: '丰赛',
    postal_code: '06000',
    is_verified: true,
  },
  {
    code: '6-09',
    province_code: '06',
    name_en: 'Chomphet District',
    name_la: 'ເມືອງຈອມເພັດ',
    name_th: 'จอมเพ็ด',
    name_zh: '钟佩',
    postal_code: '06000',
    is_verified: true,
  },
  {
    code: '6-10',
    province_code: '06',
    name_en: 'Viengkham District',
    name_la: 'ເມືອງວຽງຄຳ',
    name_th: 'เวียงคำ',
    name_zh: '永甘',
    postal_code: '06000',
    is_verified: true,
  },
  {
    code: '6-11',
    province_code: '06',
    name_en: 'Phoukhoune District',
    name_la: 'ເມືອງພູຄູນ',
    name_th: 'ภูคูน',
    name_zh: '普库恩',
    postal_code: '06000',
    is_verified: true,
  },
  {
    code: '6-12',
    province_code: '06',
    name_en: 'Phonthong District',
    name_la: 'ເມືອງໂພນທອງ',
    name_th: 'โพนทอง',
    name_zh: '丰通',
    postal_code: '06000',
    is_verified: true,
  },

  /* =======================
   HOUAPHAN (07)
   ======================= */
  {
    code: '7-01',
    province_code: '07',
    name_en: 'Xam Neua District',
    name_la: 'ເມືອງຊຳເໜືອ',
    name_th: 'ซำเหนือ',
    name_zh: '占北',
    postal_code: '07000',
    is_verified: true,
  },
  {
    code: '7-02',
    province_code: '07',
    name_en: 'Xiengkho District',
    name_la: 'ເມືອງຊຽງຄໍ້',
    name_th: 'เชียงค้อ',
    name_zh: '显科',
    postal_code: '07000',
    is_verified: true,
  },
  {
    code: '7-03',
    province_code: '07',
    name_en: 'Hiam District',
    name_la: 'ເມືອງວຽງທອງ',
    name_th: 'เวียงทอง',
    name_zh: '喜昂',
    postal_code: '07000',
    is_verified: true,
  },
  {
    code: '7-04',
    province_code: '07',
    name_en: 'Viengxay District',
    name_la: 'ເມືອງວຽງໄຊ',
    name_th: 'เวียงไซ',
    name_zh: '永赛',
    postal_code: '07000',
    is_verified: true,
  },
  {
    code: '7-05',
    province_code: '07',
    name_en: 'Houameuang District',
    name_la: 'ເມືອງຫົວເມືອງ',
    name_th: 'หัวเมือง',
    name_zh: '胡阿蒙',
    postal_code: '07000',
    is_verified: true,
  },
  {
    code: '7-06',
    province_code: '07',
    name_en: 'Samtay District',
    name_la: 'ເມືອງຊຳໃຕ້',
    name_th: 'ซำใต้',
    name_zh: '三泰',
    postal_code: '07000',
    is_verified: true,
  },
  {
    code: '7-07',
    province_code: '07',
    name_en: 'Sop Bao District',
    name_la: 'ເມືອງສົບເບົາ',
    name_th: 'สบเบ้า',
    name_zh: '索宝',
    postal_code: '07000',
    is_verified: true,
  },
  {
    code: '7-08',
    province_code: '07',
    name_en: 'Et District',
    name_la: 'ເມືອງແອດ',
    name_th: 'แอด',
    name_zh: '艾特',
    postal_code: '07000',
    is_verified: true,
  },
  {
    code: '7-09',
    province_code: '07',
    name_en: 'Kone District',
    name_la: 'ເມືອງກອັນ',
    name_th: 'ก้อน',
    name_zh: '孔',
    postal_code: '07000',
    is_verified: true,
  },
  {
    code: '7-10',
    province_code: '07',
    name_en: 'Xon District',
    name_la: 'ເມືອງຊ່ອນ',
    name_th: 'ซ้อน',
    name_zh: '逊',
    postal_code: '07000',
    is_verified: true,
  },

  /* =======================
   SAINYABULI (08)
   ======================= */
  {
    code: '8-01',
    province_code: '08',
    name_en: 'Sainyabuli District',
    name_la: 'ເມືອງໄຊຍະບູລີ',
    name_th: 'ไชยบุรี',
    name_zh: '赛雅布里',
    postal_code: '84000',
    is_verified: true,
  },
  {
    code: '8-02',
    province_code: '08',
    name_en: 'Khop District',
    name_la: 'ເມືອງຄອບ',
    name_th: 'คอบ',
    name_zh: '科普',
    postal_code: '84000',
    is_verified: true,
  },
  {
    code: '8-03',
    province_code: '08',
    name_en: 'Hongsa District',
    name_la: 'ເມືອງຫົງສາ',
    name_th: 'หงสา',
    name_zh: '宏沙',
    postal_code: '84000',
    is_verified: true,
  },
  {
    code: '8-04',
    province_code: '08',
    name_en: 'Ngeun District',
    name_la: 'ເມືອງເງິນ',
    name_th: 'เงิน',
    name_zh: '银',
    postal_code: '84000',
    is_verified: true,
  },
  {
    code: '8-05',
    province_code: '08',
    name_en: 'Xienghone District',
    name_la: 'ເມືອງຊຽງຮ່ອນ',
    name_th: 'เชียงร้อน',
    name_zh: '显洪',
    postal_code: '84000',
    is_verified: true,
  },
  {
    code: '8-06',
    province_code: '08',
    name_en: 'Phiang District',
    name_la: 'ເມືອງພຽງ',
    name_th: 'เพียง',
    name_zh: '芬昂',
    postal_code: '84000',
    is_verified: true,
  },
  {
    code: '8-07',
    province_code: '08',
    name_en: 'Parklai District',
    name_la: 'ເມືອງປາກລາຍ',
    name_th: 'ปากลาย',
    name_zh: '帕克莱',
    postal_code: '84000',
    is_verified: true,
  },
  {
    code: '8-08',
    province_code: '08',
    name_en: 'Kenethao District',
    name_la: 'ເມືອງແກ່ນທ້າວ',
    name_th: 'แก่นท้าว',
    name_zh: '克内涛',
    postal_code: '84000',
    is_verified: true,
  },
  {
    code: '8-09',
    province_code: '08',
    name_en: 'Botene District',
    name_la: 'ເມືອງບໍ່ແຕນ',
    name_th: 'บ่อแตน',
    name_zh: '博滕',
    postal_code: '84000',
    is_verified: true,
  },
  {
    code: '8-10',
    province_code: '08',
    name_en: 'Thongmyxay District',
    name_la: 'ເມືອງທົ່ງມີໄຊ',
    name_th: 'ท้องมีไซ',
    name_zh: '通密赛',
    postal_code: '84000',
    is_verified: true,
  },
  {
    code: '8-11',
    province_code: '08',
    name_en: 'Xaisathan District',
    name_la: 'ເມືອງໄຊສະຖານ',
    name_th: 'ไชยสถาน',
    name_zh: '赛萨坦',
    postal_code: '84000',
    is_verified: true,
  },

  /* =======================
   XIANGKHOUANG (09)
   ======================= */
  {
    code: '9-01',
    province_code: '09',
    name_en: 'Pek District',
    name_la: 'ເມືອງແປກ',
    name_th: 'เพ็ก',
    name_zh: '佩克',
    postal_code: '85000',
    is_verified: true,
  },
  {
    code: '9-02',
    province_code: '09',
    name_en: 'Kham District',
    name_la: 'ເມືອງຄຳ',
    name_th: 'คำ',
    name_zh: '坎',
    postal_code: '85000',
    is_verified: true,
  },
  {
    code: '9-03',
    province_code: '09',
    name_en: 'Nong Het District',
    name_la: 'ເມືອງໜອງແຮດ',
    name_th: 'หนองแฮด',
    name_zh: '农赫',
    postal_code: '85000',
    is_verified: true,
  },
  {
    code: '9-04',
    province_code: '09',
    name_en: 'Khoune District',
    name_la: 'ເມືອງຄູນ',
    name_th: 'คูน',
    name_zh: '库恩',
    postal_code: '85000',
    is_verified: true,
  },
  {
    code: '9-05',
    province_code: '09',
    name_en: 'Mok May District',
    name_la: 'ເມືອງໝອກໃໝ່',
    name_th: 'หมอกใหม่',
    name_zh: '莫克迈',
    postal_code: '85000',
    is_verified: true,
  },
  {
    code: '9-06',
    province_code: '09',
    name_en: 'Phou Kout District',
    name_la: 'ເມືອງພູກູດ',
    name_th: 'ภูคูด',
    name_zh: '普库',
    postal_code: '85000',
    is_verified: true,
  },
  {
    code: '9-07',
    province_code: '09',
    name_en: 'Phaxay District',
    name_la: 'ເມືອງຜາໄຊ',
    name_th: 'ผาไชย',
    name_zh: '帕赛',
    postal_code: '85000',
    is_verified: true,
  },

  /* =======================
   VIENTIANE PROVINCE (10)
   ======================= */
  {
    code: '10-01',
    province_code: '10',
    name_en: 'Phonhong District',
    name_la: 'ເມືອງໂພນໂຮງ',
    name_th: 'โพนโฮง',
    name_zh: '丰鸿',
    postal_code: '10000',
    is_verified: true,
  },
  {
    code: '10-02',
    province_code: '10',
    name_en: 'Thoulakhom District',
    name_la: 'ເມືອງທຸລະຄົມ',
    name_th: 'ทุละคม',
    name_zh: '图拉孔',
    postal_code: '10000',
    is_verified: true,
  },
  {
    code: '10-03',
    province_code: '10',
    name_en: 'Keo Oudom District',
    name_la: 'ເມືອງແກ້ວອຸດົມ',
    name_th: 'แก้วอุดม',
    name_zh: '克奥多姆',
    postal_code: '10000',
    is_verified: true,
  },
  {
    code: '10-04',
    province_code: '10',
    name_en: 'Kasy District',
    name_la: 'ເມືອງກາສີ',
    name_th: 'กาสี',
    name_zh: '卡西',
    postal_code: '10000',
    is_verified: true,
  },
  {
    code: '10-05',
    province_code: '10',
    name_en: 'Vangvieng District',
    name_la: 'ເມືອງວັງວຽງ',
    name_th: 'วังเวียง',
    name_zh: '万象',
    postal_code: '10000',
    is_verified: true,
  },
  {
    code: '10-06',
    province_code: '10',
    name_en: 'Feuang District',
    name_la: 'ເມືອງເຟືອງ',
    name_th: 'เฟือง',
    name_zh: '丰昂',
    postal_code: '10000',
    is_verified: true,
  },
  {
    code: '10-07',
    province_code: '10',
    name_en: 'Xanakharm District',
    name_la: 'ເມືອງຊະນະຄາມ',
    name_th: 'ชนะคาม',
    name_zh: '查那甘',
    postal_code: '10000',
    is_verified: true,
  },
  {
    code: '10-08',
    province_code: '10',
    name_en: 'Mad District',
    name_la: 'ເມືອງແມດ',
    name_th: 'แมด',
    name_zh: '马德',
    postal_code: '10000',
    is_verified: true,
  },
  {
    code: '10-09',
    province_code: '10',
    name_en: 'Viengkham District',
    name_la: 'ເມືອງວຽງຄໍາ',
    name_th: 'เวียงคำ',
    name_zh: '永甘',
    postal_code: '10000',
    is_verified: true,
  },
  {
    code: '10-10',
    province_code: '10',
    name_en: 'Hinhurp District',
    name_la: 'ເມືອງຫີນເຫີບ',
    name_th: 'หินเหิร์บ',
    name_zh: '欣赫普',
    postal_code: '10000',
    is_verified: true,
  },
  {
    code: '10-11',
    province_code: '10',
    name_en: 'Meun District',
    name_la: 'ເມືອງໝື່ນ',
    name_th: 'หมื่น',
    name_zh: '蒙',
    postal_code: '10000',
    is_verified: true,
  },

  /* =======================
   BOLIKHAMSAI (11)
   ======================= */
  {
    code: '11-01',
    province_code: '11',
    name_en: 'Pakxan District',
    name_la: 'ເມືອງປາກຊັນ',
    name_th: 'ปากซัน',
    name_zh: '帕克桑',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '11-02',
    province_code: '11',
    name_en: 'Thaphabat District',
    name_la: 'ເມືອງທ່າພະບາດ',
    name_th: 'ท่าพบาด',
    name_zh: '塔帕巴特',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '11-03',
    province_code: '11',
    name_en: 'Pakkading District',
    name_la: 'ເມືອງປາກກະດິງ',
    name_th: 'ปากกาดิง',
    name_zh: '帕克达',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '11-04',
    province_code: '11',
    name_en: 'Borikhane District',
    name_la: 'ເມືອງບໍລິຄັນ',
    name_th: 'โบริคาน',
    name_zh: '博里坎',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '11-05',
    province_code: '11',
    name_en: 'Khamkeut District',
    name_la: 'ເມືອງຄຳເກີດ',
    name_th: 'คำเกิด',
    name_zh: '坎科特',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '11-06',
    province_code: '11',
    name_en: 'Viengthong District',
    name_la: 'ເມືອງວຽງທອງ',
    name_th: 'เวียงทอง',
    name_zh: '永通',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '11-07',
    province_code: '11',
    name_en: 'Xaichamphon District',
    name_la: 'ເມືອງໄຊຈຳພອນ',
    name_th: 'ไชยจำพอน',
    name_zh: '赛占丰',
    postal_code: '86000',
    is_verified: true,
  },

  /* =======================
   KHAMMOUANE (12)
   ======================= */
  {
    code: '12-01',
    province_code: '12',
    name_en: 'Thakhek District',
    name_la: 'ເມືອງທ່າແຂກ',
    name_th: 'ท่าแขก',
    name_zh: '塔克赫克',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '12-02',
    province_code: '12',
    name_en: 'Mahaxay District',
    name_la: 'ເມືອງມະຫາໄຊ',
    name_th: 'มหาไชย',
    name_zh: '玛哈赛',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '12-03',
    province_code: '12',
    name_en: 'Nong Bok District',
    name_la: 'ເມືອງໜອງບົກ',
    name_th: 'หนองบก',
    name_zh: '农博',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '12-04',
    province_code: '12',
    name_en: 'Hineboune District',
    name_la: 'ເມືອງຫີນບູນ',
    name_th: 'หินบุน',
    name_zh: '欣布恩',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '12-05',
    province_code: '12',
    name_en: 'Yommalath District',
    name_la: 'ເມືອງຍົມມະລາດ',
    name_th: 'ยมมะลาด',
    name_zh: '永玛拉',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '12-06',
    province_code: '12',
    name_en: 'Boualapha District',
    name_la: 'ເມືອງບົວລະພາ',
    name_th: 'บัวละพา',
    name_zh: '布阿拉帕',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '12-07',
    province_code: '12',
    name_en: 'Nakai District',
    name_la: 'ມືອງນາກາຍ',
    name_th: 'นากาย',
    name_zh: '那凯',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '12-08',
    province_code: '12',
    name_en: 'Sebangphay District',
    name_la: 'ເມືອງເຊບັ້ງໄຟ',
    name_th: 'เซบังไฟ',
    name_zh: '色邦派',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '12-09',
    province_code: '12',
    name_en: 'Xaibouathong District',
    name_la: 'ເມືອງໄຊບົວທອງ',
    name_th: 'ไชบัวทอง',
    name_zh: '赛布通',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '12-10',
    province_code: '12',
    name_en: 'Kounkham District',
    name_la: 'ເມືອງຄູນຄຳ',
    name_th: 'คูนคำ',
    name_zh: '库恩康',
    postal_code: '86000',
    is_verified: true,
  },

  /* =======================
   SAVANNAKHET (13)
   ======================= */
  {
    code: '13-01',
    province_code: '13',
    name_en: 'Kaysone Phomvihane District',
    name_la: 'ເມືອງໄກສອນ ພົມວິຫານ',
    name_th: 'ไกสอน พมวิหาน',
    name_zh: '凯索冯维汉',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '13-02',
    province_code: '13',
    name_en: 'Outhoumphone District',
    name_la: 'ເມືອງອຸທຸມພອນ',
    name_th: 'อูทูมโพน',
    name_zh: '乌通蓬',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '13-03',
    province_code: '13',
    name_en: 'Atsaphangthong District',
    name_la: 'ເມືອງອາດສະພັງທອງ',
    name_th: 'อัตสาพังทอง',
    name_zh: '阿萨蓬通',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '13-04',
    province_code: '13',
    name_en: 'Phine District',
    name_la: 'ເມືອງພີນ',
    name_th: 'พีน',
    name_zh: '品',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '13-05',
    province_code: '13',
    name_en: 'Seponh District',
    name_la: 'ເມືອງເຊໂປນ',
    name_th: 'เซโพน',
    name_zh: '塞蓬',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '13-06',
    province_code: '13',
    name_en: 'Nong District',
    name_la: 'ເມືອງນອງ',
    name_th: 'นอง',
    name_zh: '农',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '13-07',
    province_code: '13',
    name_en: 'Thapangthong District',
    name_la: 'ເມືອງທ່າປາງທອງ',
    name_th: 'ท่าปางทอง',
    name_zh: '塔潘通',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '13-08',
    province_code: '13',
    name_en: 'Songkhone District',
    name_la: 'ເມືອງສອງຄອນ',
    name_th: 'สองคอน',
    name_zh: '松康',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '13-09',
    province_code: '13',
    name_en: 'Champhone District',
    name_la: 'ເມືອງຈຳພອນ',
    name_th: 'จำพอน',
    name_zh: '占丰',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '13-10',
    province_code: '13',
    name_en: 'Xonaboury District',
    name_la: 'ເມືອງຊົນນະບູລີ',
    name_th: 'ชนบุรี',
    name_zh: '雄那布里',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '13-11',
    province_code: '13',
    name_en: 'Xayboury District',
    name_la: 'ເມືອງໄຊບູລີ',
    name_th: 'ไชบุรี',
    name_zh: '赛布里',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '13-12',
    province_code: '13',
    name_en: 'Viraboury District',
    name_la: 'ເມືອງວີລະບຸລີ',
    name_th: 'วีรบุรี',
    name_zh: '威拉布里',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '13-13',
    province_code: '13',
    name_en: 'Assaphone District',
    name_la: 'ເມືອງອາດສະພອນ',
    name_th: 'อาดสาพอน',
    name_zh: '阿萨蓬',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '13-14',
    province_code: '13',
    name_en: 'Xonboury District',
    name_la: 'ເມືອງໄຊພູທອງ',
    name_th: 'ไชพูทอง',
    name_zh: '雄布通',
    postal_code: '86000',
    is_verified: true,
  },
  {
    code: '13-15',
    province_code: '13',
    name_en: 'Thaphalanxay District',
    name_la: 'ເມືອງພະລານໄຊ',
    name_th: 'ท่าพลานไซ',
    name_zh: '塔帕兰赛',
    postal_code: '86000',
    is_verified: true,
  },

  /* =======================
   SALAVAN (14)
   ======================= */
  {
    code: '14-01',
    province_code: '14',
    name_en: 'Saravane District',
    name_la: 'ເມືອງສາລະວັນ',
    name_th: 'สาละวัน',
    name_zh: '沙拉万',
    postal_code: '87000',
    is_verified: true,
  },
  {
    code: '14-02',
    province_code: '14',
    name_en: 'Ta Oy District',
    name_la: 'ເມືອງຕະໂອ້ຍ',
    name_th: 'ตะโอย',
    name_zh: '塔奥伊',
    postal_code: '87000',
    is_verified: true,
  },
  {
    code: '14-03',
    province_code: '14',
    name_en: 'Toumlane District',
    name_la: 'ເມືອງຕຸ້ມລານ',
    name_th: 'ตูมลาน',
    name_zh: '图姆兰',
    postal_code: '87000',
    is_verified: true,
  },
  {
    code: '14-04',
    province_code: '14',
    name_en: 'Lakhonepheng District',
    name_la: 'ເມືອງລະຄອນເພັງ',
    name_th: 'ละคอนเพ็ง',
    name_zh: '拉孔彭',
    postal_code: '87000',
    is_verified: true,
  },
  {
    code: '14-05',
    province_code: '14',
    name_en: 'Vapy District',
    name_la: 'ເມືອງວາປີ',
    name_th: 'วาปี',
    name_zh: '瓦皮',
    postal_code: '87000',
    is_verified: true,
  },
  {
    code: '14-06',
    province_code: '14',
    name_en: 'Khongsedone District',
    name_la: 'ເມືອງຄົງເຊໂດນ',
    name_th: 'คงเซโดน',
    name_zh: '孔赛东',
    postal_code: '87000',
    is_verified: true,
  },
  {
    code: '14-07',
    province_code: '14',
    name_en: 'Lao Ngam District',
    name_la: 'ເມືອງເລົ່າງາມ',
    name_th: 'เล่างาม',
    name_zh: '老昂',
    postal_code: '87000',
    is_verified: true,
  },
  {
    code: '14-08',
    province_code: '14',
    name_en: 'Sa Mouay District',
    name_la: 'ເມືອງສະມ້ວຍ',
    name_th: 'สะม้วย',
    name_zh: '萨穆艾',
    postal_code: '87000',
    is_verified: true,
  },

  /* =======================
   SEKONG (15)
   ======================= */
  {
    code: '15-01',
    province_code: '15',
    name_en: 'La Mam District',
    name_la: 'ເມືອງລະມາມ',
    name_th: 'ละมาม',
    name_zh: '拉玛姆',
    postal_code: '88000',
    is_verified: true,
  },
  {
    code: '15-02',
    province_code: '15',
    name_en: 'Kaleum District',
    name_la: 'ເມືອງກະເລິມ',
    name_th: 'กาเลิม',
    name_zh: '卡勒姆',
    postal_code: '88000',
    is_verified: true,
  },
  {
    code: '15-03',
    province_code: '15',
    name_en: 'Dak Cheung District',
    name_la: 'ເມືອງດາກຈຶງ',
    name_th: 'ดากจึง',
    name_zh: '达克中',
    postal_code: '88000',
    is_verified: true,
  },
  {
    code: '15-04',
    province_code: '15',
    name_en: 'Tha Teng District',
    name_la: 'ເມືອງທ່າແຕງ',
    name_th: 'ท่าแตง',
    name_zh: '塔腾',
    postal_code: '88000',
    is_verified: true,
  },

  /* =======================
   ATTAPEU (16)
   ======================= */
  {
    code: '16-01',
    province_code: '16',
    name_en: 'Attapeu District',
    name_la: 'ເມືອງອັດຕະປື',
    name_th: 'อัตตะปือ',
    name_zh: '阿塔普',
    postal_code: '88000',
    is_verified: true,
  },
  {
    code: '16-02',
    province_code: '16',
    name_en: 'Samakkhixay District',
    name_la: 'ເມືອງສຳມັກຂີ້ໄຊ',
    name_th: 'สามัคคีไซ',
    name_zh: '三康西',
    postal_code: '88000',
    is_verified: true,
  },
  {
    code: '16-03',
    province_code: '16',
    name_en: 'Sanamxay District',
    name_la: 'ເມືອງສານຳໄຊ',
    name_th: 'สาน้ำไซ',
    name_zh: '萨南赛',
    postal_code: '88000',
    is_verified: true,
  },
  {
    code: '16-04',
    province_code: '16',
    name_en: 'Xaysetha District',
    name_la: 'ເມືອງໄຊເສຖາ',
    name_th: 'ไชเสถีย',
    name_zh: '赛赛塔',
    postal_code: '88000',
    is_verified: true,
  },
  {
    code: '16-05',
    province_code: '16',
    name_en: 'Phouvong District',
    name_la: 'ເມືອງພູວົງ',
    name_th: 'ภูวง',
    name_zh: '富翁',
    postal_code: '88000',
    is_verified: true,
  },

  /* =======================
   SAVANNAKHET (17)
   ======================= */
  {
    code: '17-01',
    province_code: '17',
    name_en: 'Xayabury District',
    name_la: 'ເມືອງໄຊບູລີ',
    name_th: 'ไชบุรี',
    name_zh: '赛布里',
    postal_code: '88000',
    is_verified: true,
  },

  /* =======================
   XAISOMBOUN (18)
   ======================= */
  {
    code: '18-01',
    province_code: '18',
    name_en: 'Hom District',
    name_la: 'ເມືອງຮອມ',
    name_th: 'หอม',
    name_zh: '洪',
    postal_code: '85000',
    is_verified: true,
  },
  {
    code: '18-02',
    province_code: '18',
    name_en: 'Long District',
    name_la: 'ເມືອງລົງ',
    name_th: 'ลอง',
    name_zh: '龙',
    postal_code: '85000',
    is_verified: true,
  },
  {
    code: '18-03',
    province_code: '18',
    name_en: 'Phoukhoun District',
    name_la: 'ເມືອງພູຄູນ',
    name_th: 'ภูคูน',
    name_zh: '普昆',
    postal_code: '85000',
    is_verified: true,
  },
  {
    code: '18-04',
    province_code: '18',
    name_en: 'Xaysomboun District',
    name_la: 'ເມືອງໄຊສົມບູນ',
    name_th: 'ไชสมบุญ',
    name_zh: '赛松本',
    postal_code: '85000',
    is_verified: true,
  },
];
